// NAMES START ----------------------
//27 female and 27 male names & surnames

const maleNames = [
    "Adam",
    "Bedřich",
    "Kazimír",
    "Kamil",
    "Miroslav",
    "Tomáš",
    "Mojmir",
    "Jakub",
    "Samuel",
    "Michal",
    "Oliver",
    "Matěj",
    "Peter",
    "Šimon",
    "Patřik",
    "Richard",
    "Dávid",
    "Alex",
    "Josef",
    "Kvido",
    "Arnošt",
    "Hugo",
    "Dušan",
    "Vojtěch",
    "Čeněk",
    "Libor",
    "Ludvík",
];

const femaleNames = [
    "Gabriela",
    "Viktorie",
    "Anděla",
    "Růžena",
    "Miloslava",
    "Vanda",
    "Veronika",
    "Nela",
    "Erika",
    "Ema",
    "Marcela",
    "Alexandra",
    "Evžénie",
    "Jaroslava",
    "Olga",
    "Martina",
    "Drahomíra",
    "Marta",
    "Kristýna",
    "Petra",
    "Hana",
    "Helena",
    "Zlata",
    "Ludmila",
    "Sabina",
    "Renáta",
    "Silvie",
];

const maleSurnames = [
    "Novák",
    "Svoboda",
    "Novotný",
    "Dvořák",
    "Černý",
    "Procházka",
    "Kučera",
    "Veselý",
    "Horák",
    "Němec",
    "Marko",
    "Pokorný",
    "Pospíšil",
    "Král",
    "Jelínek",
    "Růžička",
    "Fiala",
    "Sedláček",
    "Kolář",
    "Urban",
    "Šimko",
    "Vaněk",
    "Kopecký",
    "Zeman",
    "Čech",
    "Malý",
    "Štěpánek",
    "Konečný",
    
];

const femaleSurnames = [
    "Nováková",
    "Svobodová",
    "Novotná",
    "Dvořáková",
    "Černá",
    "Procházková",
    "Kučerová",
    "Veselá",
    "Horáková",
    "Němcová",
    "Marková",
    "Pokorná",
    "Pospíšilová",
    "Králová",
    "Jelínková",
    "Růžičková",
    "Fialová",
    "Sedláčková",
    "Kolářová",
    "Urbanová",
    "Šimková",
    "Vaňková",
    "Kopecká",
    "Zemanová",
    "Čechová",
    "Malá",
    "Štěpánková",
    "Konečná",
];


// NAMES END -----------------------

const namesList = {
    maleNames,
    femaleNames,
    maleSurnames,
    femaleSurnames
}

export default namesList;